version: '3'
services:
  bot:
    build: ./bot
    ports:
      - "8011:8000"
    command: python /home/bot/app.py
    environment:
      CHANNEL_SECRET: ${CHANNEL_SECRET}
      CHANNEL_TOKEN: ${CHANNEL_TOKEN}
      VIRTUAL_HOST: woodbot.wild-family.cf
    volumes:
      - ./bot:/home/bot
    links: 
      - postgres
  postgres:
    build: ./postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: docker
    volumes: 
      - ./postgres/create_table.sql:/tmp/create_table.sql
      - ./postgres/insert_data.sql:/tmp/insert_data.sql
networks:
    default:
        external:
          name: my_network